### ISSUE TITLE
[FEATURE PROPOSAL] Deployments to Chocolatey/WinGet

### ISSUE THREAD

**Issue by gbakeman** [CodingWonders/DISMTools#93]
**Describe the solution you'd like**
Just found out about this project, and love that it's made in VB.Net. It would be great to have deployments to Chocolatey & WinGet for easy releases and updating. Thank you!

Btw, I didn't mean to add the `good first issue` label to this... I make no guarantees of quality here 😅

**Comment by CodingWonders** [comment]
I would need to learn how to publish that to WinGet!

Now, while installing DISMTools is easy, log files will remain after uninstalling it. I want to find a fix for that before uploading it to WinGet or Chocolatey. I'll consider that suggestion though.

Thanks!

**Comment by gbakeman** [comment]
Fair enough. I'd like to contribute, but of course have other projects in motion. Hopefully sometime in the future if you haven't by then. Thanks for your work.

**Comment by CodingWonders** [comment]
> Fair enough. I'd like to contribute, but of course have other projects in motion. Hopefully sometime in the future if you haven't by then. Thanks for your work.

Alright, take your time with your additional projects.

**Comment by CodingWonders** [comment]
A manifest has been created that can be used to deploy it to WinGet:

<p align="center">
  <img src="https://github.com/CodingWonders/DISMTools/assets/101426328/e70f735b-c010-4a16-b1ca-b516eb48637e" />
</p>

```yaml
# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: CodingWondersSoftware.DISMTools.Stable
PackageVersion: "0.4"
PackageLocale: en-US
Publisher: CodingWonders Software
PublisherUrl: https://github.com/CodingWonders
PublisherSupportUrl: https://github.com/CodingWonders
Author: CodingWonders
PackageName: DISMTools
PackageUrl: https://github.com/CodingWonders/DISMTools
License: GPLv3
LicenseUrl: https://github.com/CodingWonders/DISMTools/blob/stable/LICENSE
Copyright: (c) 2022-2024. CodingWonders Software
ShortDescription: The connected place for Windows system administration
Description: DISMTools is an advanced front-end for the Deployment Image Servicing and Management (DISM) tool, with support for projects and installations of any kind (whether it is your active installation or installations on any drive). DISMTools focuses on compatibility, with Windows image support starting from Windows 7, and personalization, letting you customize it the way you want by configuring settings like the DISM executable to use, color modes, languages, and more. The combination of the DISM executable plus a managed version of the DISM API (thanks to Jeff Kluge (jeffkl) for maintaining it) also provides rich functionality at speed.
Moniker: DISMTools
Tags:
- dism
- sysadmin
- windows
- gui
ReleaseNotes: 'Some key features of DISMTools 0.4 include: a new design of the home and project screens, offline installation mode capabilities and Help documentation contents. To view the full release notes, head over to https://github.com/CodingWonders/DISMTools/releases/tag/v0.4_stable.'
ReleaseNotesUrl: https://github.com/CodingWonders/DISMTools/releases/tag/v0.4_stable
InstallationNotes: Enjoy using DISMTools! If you're new to image servicing, or come from other tools, check out the help documentation. If you encounter an issue, don't hesitate to send feedback at https://github.com/CodingWonders/DISMTools/issues/new/choose
ManifestType: defaultLocale
ManifestVersion: 1.5.0

```
